### ISSUE TITLE
Integration missing from configuration/Integration

### ISSUE THREAD

**Issue by totoantibes** [mawinkler/astroweather#1]
Hi,

was looking forward to the HACS on my HA on Docker. However after installing it on HACS ( and restarting) i cannot see the configuration panel in the integration list.

Any ideas of where it may have gone?
thx

**Comment by mawinkler** [comment]
Hi @totoantibes 

interesting. I just recreated a fresh Home Assistant installation from scratch, redeployed HACS and waited for the initialization tasks to finish. Then added my AstroWeather in HACS. Restart of Home Assistant, then Configuration and Integration. I was flawlessly able to install AstroWeather. Maybe you didn't restart HASS?

**Comment by totoantibes** [comment]
weird. I now have it on my available integrations. this can be closed... (not sure if i have was too impatient...
Thanks for following up.

Clear Skies!
