### ISSUE TITLE
Sunrise and sunset times are wrong 

### ISSUE THREAD

**Issue by OldSpeedy** [mawinkler/astroweather#12]
While all weather forcast data seem to be correct for my geolocation, the times for sunrise and sunset aren't.
The astroweather intergration says for today for sunrise 04:26 and sunset 20:18, but it should be (around Berlin for sunrise 06:19 and 18:11for sunset )

**Comment by mawinkler** [comment]
The time of day shown for sunrise and sunset are calculated for the astronomical twilight. This means that they are calculated for 18° below the horizon.

**Comment by OldSpeedy** [comment]
Oh, sorry! My bad. I didn't know it. I'm a bloody beginner with astronomy.
