### ISSUE TITLE
0.22.0 Fails To Build on 2022.7.2

### ISSUE THREAD

**Issue by ejpenney** [mawinkler/astroweather#17]
Tried installing the update today and it blew up during startup:

```
2022-07-10 08:38:32 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package pyastroweatherio==0.22.0: error: subprocess-exited-with-error
  
  × Building wheel for h3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/tmp/pip-build-env-5al1vlj1/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-5al1vlj1/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-5al1vlj1/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects
2022-07-10 08:39:47 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package pyastroweatherio==0.22.0: error: subprocess-exited-with-error
  
  × Building wheel for h3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/tmp/pip-build-env-o039bfh3/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-o039bfh3/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-o039bfh3/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects
2022-07-10 08:40:59 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package pyastroweatherio==0.22.0: error: subprocess-exited-with-error
  
  × Building wheel for h3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/tmp/pip-build-env-9cepydg_/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-9cepydg_/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-9cepydg_/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects
2022-07-10 08:40:59 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration astroweather: Requirements for astroweather not found: ['pyastroweatherio==0.22.0'].
```

Rolled back to 0.21.0 and everything worked fine.

**Comment by mawinkler** [comment]
Hmm, interesting. My dev environment is on 2022.8 and my live HA is on 2022.7.2. Did you try to restart HA?

**Comment by danielbanfi47** [comment]
For me is the same after I restarted the HA (core-2022.7.2) after I updated to 0.22.0

**Comment by ejpenney** [comment]
I just tried restarting a few times with no success.  Error looks the same each time.  Might be worth noting the failure causes this message in Notifications (obfuscated my URL):

```
Invalid config
The following integrations and platforms could not be set up:

[astroweather](https://github.com/mawinkler/astroweather) ([Show logs](https://<URL>/config/logs?filter=astroweather))
Please check your config and [logs](https://<URL>/config/logs).

4 minutes ago
```

**Comment by mawinkler** [comment]
If my gut feeling is right, I think I know the reason for the error. I'm going to create a new pyastroweatherio for you to try tomorrow.

**Comment by MisterTFM** [comment]
Same as above, trying to install Astroweather, it gets stuck:

![ScreenHunter 356](https://user-images.githubusercontent.com/74779407/178408628-9466cd99-f5ec-452c-b53a-2d9a61ef2f43.jpg)
![ScreenHunter 355](https://user-images.githubusercontent.com/74779407/178408642-f90e5f50-35f4-4a08-85a3-5d4026c26a3c.jpg)

**Comment by mawinkler** [comment]
Please try the following:
change the `requirements` and `version` within the file `custom-components/astroweather/manifest.json` to:
```json
{
    "domain": "astroweather",
    "name": "AstroWeather",
    "version": "0.22.0",
    "documentation": "https://github.com/mawinkler/astroweather",
    "issue_tracker": "https://github.com/mawinkler/astroweather/issues",
    "config_flow": true,
    "dependencies": [],
    "codeowners": [
        "@mawinkler"
    ],
    "requirements": [
        "pyastroweatherio==0.22.1.dev1"
    ],
    "iot_class": "cloud_polling"
}
```

**Comment by LuckyTriple7** [comment]
Thx, but does not work for me:

2022-07-12 08:14:03 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package pyastroweatherio==0.22.1.dev1: error: subprocess-exited-with-error
  
  Ã— Building wheel for h3 (pyproject.toml) did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [9 lines of output]
        File "/tmp/pip-build-env-mwlbywbr/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-mwlbywbr/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-mwlbywbr/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects

**Comment by mawinkler** [comment]
Honestly, I have no idea what's wrong. I just started a completely new home assistant container 2022.7.3 from scratch (on a different host), configured HACS, added Astroweather and it just works without any complaints. At the moment I cannot replicate your problems.

I did remove the dependency on NumPy which I introduced in 0.22 in the dev pyastroweatherio release from above and now calculate the ln() via the built-in Decimals. Apparently, this didn't help.

If you have any idea, please advise.

**Comment by mawinkler** [comment]
May I ask how you run your HASS?

**Comment by ejpenney** [comment]
It's a supervised setup on a Raspberry Pi.

**Comment by MisterTFM** [comment]
> Please try the following: change the `requirements` and `version` within the file `custom-components/astroweather/manifest.json` to:
> 
> ```json
> {
>     "domain": "astroweather",
>     "name": "AstroWeather",
>     "version": "0.22.0",
>     "documentation": "https://github.com/mawinkler/astroweather",
>     "issue_tracker": "https://github.com/mawinkler/astroweather/issues",
>     "config_flow": true,
>     "dependencies": [],
>     "codeowners": [
>         "@mawinkler"
>     ],
>     "requirements": [
>         "pyastroweatherio==0.22.1.dev1"
>     ],
>     "iot_class": "cloud_polling"
> }
> ```

This did not work for me either.

**Comment by mawinkler** [comment]
> > Please try the following: change the `requirements` and `version` within the file `custom-components/astroweather/manifest.json` to:
> > ```json
> > {
> >     "domain": "astroweather",
> >     "name": "AstroWeather",
> >     "version": "0.22.0",
> >     "documentation": "https://github.com/mawinkler/astroweather",
> >     "issue_tracker": "https://github.com/mawinkler/astroweather/issues",
> >     "config_flow": true,
> >     "dependencies": [],
> >     "codeowners": [
> >         "@mawinkler"
> >     ],
> >     "requirements": [
> >         "pyastroweatherio==0.22.1.dev1"
> >     ],
> >     "iot_class": "cloud_polling"
> > }
> > ```
> 
> This did not work for me either.
> 
> Commenting out from my config.yaml: (Left over from preevios astroweather integration install.)
> 
> # - platform: season
> # type: astronomical
> The "check configuration" becomes valid, and no longer loops forever.

Plantform season has nothing to do with astroweather

**Comment by jds11111** [comment]
I had to delete the integration because it was preventing HA from completing a restart.  Saw some similar errors.

**Comment by mawinkler** [comment]
As of now, it seems to be somehow related to Rpi installations of HassOS / supervised.
Please try installing the `pyastroweatherio` package on Hass OS directly to get some more detail about the error and report back.
`pip install pyastroweatherio`

**Comment by LuckyTriple7** [comment]
Using legacy 'setup.py install' for pyastroweatherio, since package 'wheel' is not installed.                                                                                                                                            
Using legacy 'setup.py install' for pyephem, since package 'wheel' is not installed.                                                                                                                                                     
Building wheels for collected packages: h3                                                                                                                                                                                               
  Building wheel for h3 (pyproject.toml) ... error                                                                                                                                                                                       
  error: subprocess-exited-with-error                                                                                                                                                                                                    
                                                                                                                                                                                                                                         
  × Building wheel for h3 (pyproject.toml) did not run successfully.                                                                                                                                                                     
  │ exit code: 1                                                                                                                                                                                                                         
  ╰─> [66 lines of output]                                                                                                                                                                                                               
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                         
      --------------------------------------------------------------------------------                                                                                                                                                   
      -- Trying "Ninja" generator                                                                                                                                                                                                        
      --------------------------------                                                                                                                                                                                                   
      ---------------------------                                                                                                                                                                                                        
      ----------------------                                                                                                                                                                                                             
      -----------------                                                                                                                                                                                                                  
      ------------                                                                                                                                                                                                                       
      -------                                                                                                                                                                                                                            
      --                                                                                                                                                                                                                                 
      Not searching for unused variables given on the command line.                                                                                                                                                                      
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.                                                               
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-yezx657l/h3_01f5cb034a39436b859c7a04478e0768/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-yezx657l/h3_01f5cb034a39436b859c7a04478e0768/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - failure
      --------------------------------------------------------------------------------
      
      ********************************************************************************
      scikit-build could not get a working generator for your system. Aborting build.
      
      Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
      But scikit-build does *NOT* know how to install it on alpine
      
      To build compliant wheels, consider using the manylinux system described in PEP-513.
      Get it with "dockcross/manylinux-x64" docker image:
      
        https://github.com/dockcross/dockcross#readme
      
      For more details, please refer to scikit-build documentation:
      
        http://scikit-build.readthedocs.io/en/latest/generators.html#linux
      
      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
Failed to build h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects
➜  ~

**Comment by mawinkler** [comment]
> Using legacy 'setup.py install' for pyastroweatherio, since package 'wheel' is not installed. Using legacy 'setup.py install' for pyephem, since package 'wheel' is not installed. Building wheels for collected packages: h3 Building wheel for h3 (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for h3 (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [66 lines of output]
> 
> ```
>   --------------------------------------------------------------------------------                                                                                                                                                   
>   -- Trying "Ninja" generator                                                                                                                                                                                                        
>   --------------------------------                                                                                                                                                                                                   
>   ---------------------------                                                                                                                                                                                                        
>   ----------------------                                                                                                                                                                                                             
>   -----------------                                                                                                                                                                                                                  
>   ------------                                                                                                                                                                                                                       
>   -------                                                                                                                                                                                                                            
>   --                                                                                                                                                                                                                                 
>   Not searching for unused variables given on the command line.                                                                                                                                                                      
>   CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.                                                               
>   -- Configuring incomplete, errors occurred!
>   See also "/tmp/pip-install-yezx657l/h3_01f5cb034a39436b859c7a04478e0768/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
>   --
>   -------
>   ------------
>   -----------------
>   ----------------------
>   ---------------------------
>   --------------------------------
>   -- Trying "Ninja" generator - failure
>   --------------------------------------------------------------------------------
>   
>   
>   
>   --------------------------------------------------------------------------------
>   -- Trying "Unix Makefiles" generator
>   --------------------------------
>   ---------------------------
>   ----------------------
>   -----------------
>   ------------
>   -------
>   --
>   Not searching for unused variables given on the command line.
>   CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
>   -- Configuring incomplete, errors occurred!
>   See also "/tmp/pip-install-yezx657l/h3_01f5cb034a39436b859c7a04478e0768/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
>   --
>   -------
>   ------------
>   -----------------
>   ----------------------
>   ---------------------------
>   --------------------------------
>   -- Trying "Unix Makefiles" generator - failure
>   --------------------------------------------------------------------------------
>   
>   ********************************************************************************
>   scikit-build could not get a working generator for your system. Aborting build.
>   
>   Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
>   But scikit-build does *NOT* know how to install it on alpine
>   
>   To build compliant wheels, consider using the manylinux system described in PEP-513.
>   Get it with "dockcross/manylinux-x64" docker image:
>   
>     https://github.com/dockcross/dockcross#readme
>   
>   For more details, please refer to scikit-build documentation:
>   
>     http://scikit-build.readthedocs.io/en/latest/generators.html#linux
>   
>   ********************************************************************************
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for h3 Failed to build h3 ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based projects

What kind of hass environment did you try on?

**Comment by LuckyTriple7** [comment]
Rpi 4

Home Assistant OS 8.2

**Comment by mawinkler** [comment]
Hi,
good news - the issue should be fixed. If you're feeling adventurous redownload astroweather from the main branch, delete the integration via devices and services, restart hass and add the integration again. It should now work on all hass variants since I removed the dependency to `timezonefinder` and `h3`. Tested the container running on Ubuntu and HassOS on RPi 4.

I didn't find the time to create new releases so far but will do it later this evening after some positive feedback, hopefully.

*From the changelog:*
### Changes

- Calculate the timezone of the AstroWeather instance based on configured timezone. This makes it possible to configure multiple instances of AstroWeather for different locations with potentially different time zones.

### Fixes

- [Issue #16](https://github.com/mawinkler/astroweather/issues/16) and [Issue #17](https://github.com/mawinkler/astroweather/issues/17): The introduction of the module [timezonefinder](https://github.com/jannikmi/timezonefinder) with it's nested dependency to [py-h3](https://github.com/uber/h3-py) failed while compiling the `c`-module h3 on some home assistant deployment variants (e.g. Home Assistant Operating System on RPi). The config flow now allows to select the timezone for the specific AstroWeather instance for which reason the dependency to `timezonefinder` is not required anymore.

### Breaking Changes

- The config flow now requires an additional config entry. To upgrade from any previous version please delete the integration and add it again via the `Devices & Services` section of your Home Assistant

**Comment by MisterTFM** [comment]
I deleted my old astroweather folder, created a new one, then individually downloaded all the required files.  I couldn't find a ZIP file to download.

Rebooted and got the integration to load and configure.

Downloaded the custom Lovelace astroweather card files and added the following card as discribed in

type: custom:astroweather-card
entity: weather.astroweather_LONGITUTE_LATITUDE
name: AstroWeather
forecast: true
deepskydetails: true
details: true
current: true
number_of_forecasts: '7

But then got stumped when I kept getting an error on

weather.astroweather_LONGITUTE_LATITUDE

Until I realized I needed to substitute the LONGITUTE and LATITUDE to my correct values as seen in the list of entities.


Also, on this custom card, the current temp at the top is showing 90°C and the correct value should be 90 °F.


Thanks for correcting the astroweather integration.


Tom

________________________________
