### ISSUE TITLE
No plug-in/integration available

### ISSUE THREAD

**Issue by justi** [mawinkler/astroweather#20]
I've tried to add AstroWeather to my new HomeAssistant.

In readme:
HACS installation
This Integration is part of the default HACS store, so go to the HACS page and search for AstroWeather within the integrations.

Neither within the integrations nor plug-ins, AstroWeather appears.

HomeAssistant OS 9.3

**Comment by mawinkler** [comment]
I just rechecked with a new hass instance running in docker, it shows up in hacs as expected within the integration section when searching for it. I do not have a hass os installation here right now to easily test it.

**Comment by mawinkler** [comment]
no more comments, so closing.
