### ISSUE TITLE
Moon phase smaller/larger

### ISSUE THREAD

**Issue by filikun** [mawinkler/astroweather#24]
Hey! Just wonder if we could have a sensor or attribute that tells if the moon is getting larger/smaller? Not sure what the English name is for it but it would be neat to tell if the moon is heading for a new moon or full moon next. 

I guess this could be made with a `trend` sensor but would love to have it integrated.

**Comment by mawinkler** [comment]
Hmm, there is an integration moon available telling you the moon phase. Currently it's waxing gibbous. 

Not sure if this functionality is needed in AstroWeather additionally.?
