### ISSUE TITLE
Warning for transparencey sensor when running core 2023.2.2

### ISSUE THREAD

**Issue by tomlut** [mawinkler/astroweather#25]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:608
Integration: Sensor (documentation, issues)
First occurred: 23:07:31 (1 occurrences)
Last logged: 23:07:31

Sensor sensor.astroweather_transparency_plain has device class None, state class None and unit mag thus indicating it has a numeric value; however, it has the non-numeric value: 0.5-0.6 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by mawinkler** [comment]
Thank you for reporting.
Fixed it in the main branch. Releases will follow.

**Comment by mawinkler** [comment]
issue solved, closing it.

**Comment by tomlut** [comment]
Thanks for the quick resolution Marcus.
