### ISSUE TITLE
Q: binary_sensor.astroweather_deep_sky_view activation conditions?

### ISSUE THREAD

**Issue by tomlut** [mawinkler/astroweather#29]
I have never seen `binary_sensor.astroweather_deep_sky_view` turn on despite some very good seeing conditions. What are the requirements for this binary sensor to turn on?

**Comment by mawinkler** [comment]
Currently, it gets true if the condition is >= 75%. The original intention was something like if it's on then move the scope outside :-)

**Comment by tomlut** [comment]
Yeah I have an automation set up to alert me at astronomical dusk if the binary sensor is on, but it has never occurred.

**Comment by mawinkler** [comment]
<img width="2140" alt="deepskyview" src="https://user-images.githubusercontent.com/16704258/234178572-7c46a020-e06f-4469-a6f7-5a77d9b3de2c.png">
So, this graph shows when the sensor turned on for me in the last year. In other words conditions since September 2022 where pretty bad :-(.
