### ISSUE TITLE
Astroweather is not found among the integrations

### ISSUE THREAD

**Issue by veghlaszlo** [mawinkler/astroweather#3]
Hi,
After installing and rebooting I can't find it in the integrations

**Comment by mawinkler** [comment]
How did you install the integration? Manually or by HACS? If manually, where did you put it?

**Comment by veghlaszlo** [comment]
By HACS

**Comment by veghlaszlo** [comment]
I restarted it again this morning and it appeared in the integrations

**Comment by mawinkler** [comment]
hass restart

**Comment by veghlaszlo** [comment]
I restarted it ten times after installation. ☹️

**Comment by mawinkler** [comment]
Hmm, I don't have a real explanation for this. Have you seen anything in the home-assistant.log?
Googling a little on that issue indicates, that it could have been the browser cache, whereby I never experienced that problem.
