### ISSUE TITLE
Add documentation / description for sensor.astroweather_deepsky_forecast_today_plain

### ISSUE THREAD

**Issue by freeDom-** [mawinkler/astroweather#31]
Sensor value is e.g. Good-Excellent-Good.What does first, second and third value mean? Is this for different times during the night? Does this mean seeing, athmospheric transparency and clouds? Would be nice to have it in the documentation and if the sensor would have a more meaningful name / description.

**Comment by mawinkler** [comment]
Sorry that it took a while. If you have a look on the graph, there should be three * around midnight. This matches with the plain text:
<img width="443" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/631b9e35-f219-4fd8-90bd-8bd6a06fafdc">
In this case `Poor-Poor-Fair`
Tomorrow `Excellent-Good-Excellent`

**Comment by freeDom-** [comment]
Thanks for your reply!
Okay, so it is the plain text description for the conditions at 20:00 23:00 and 02:00?
This makes sense, but it would be great if it would be documented somewhere...

If you confirm this information I can create a Pull Request adding the documentation.
