### ISSUE TITLE
unit of wind speed does not update the value when changing

### ISSUE THREAD

**Issue by el97** [mawinkler/astroweather#33]
The value of wind speed does not change. It looks like the value isn't changing no matter if I choose km/h, mp/h or m/s. I compared with the met.no integration and it looks like astroweather only shows the unit in km/h.

**Comment by mawinkler** [comment]
It's m/s on my side. Where do you choose/change the unit?
<img width="401" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/5b06fe93-7261-4baf-a2ae-3a7794bcf33c">
<img width="1094" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/640134fe-80cf-4035-9122-80ac5ecf7bcc">
Screenshots are from my current core redesign, work in progress...

**Comment by el97** [comment]
Oh, I see what I did wrong here... I changed the unit on the weather entity, not the sensor.astroweather_10m_wind_speed. It would be great if you removed the options you can make on the weather entity to avoid confusion.

**Comment by mawinkler** [comment]
So, changing the units in a weather entity is something new in home assistant. I don't really know how to deal with this or how to disable this. AstroWeather sets the native units for the sensors and the card checks for the configured unit in the system. As an example: if the system configured length unit is `km` the wind speed will be `m/s`. If length is not `km` I calculate `mph` from the internally used `m/s`.
This means changing the wind speed unit in the weather entity does not have an effect.

Maybe check the latest release [v0.31.0](https://github.com/mawinkler/astroweather/releases/tag/v0.31.0).

**Comment by mawinkler** [comment]
Closing as this should be fixed with the above version. If it's not resolved, please let me know. 👍
