### ISSUE TITLE
Weather entity is unavailable 

### ISSUE THREAD

**Issue by L4p3K** [mawinkler/astroweather#35]
Same problem than in March #28, deleted both integration and card and reinstalled both, but the weather entity is not provided by the integration. Worked fine before. 46 entities are being provided, one binary sensor and 45 sensors, but no weather entity.

**Comment by mawinkler** [comment]
Please try the new release [0.30.0](https://github.com/mawinkler/astroweather/releases/tag/v0.30.0). If problems persist please post some logs.

**Comment by astroimagineer** [comment]
Same here. Astroweather update is the entity published. Astroweather itself is not published.

**Comment by darth-aragoth** [comment]
The same here. My error log:

```
Logger: homeassistant.setup
Source: setup.py:347
First occurred: 23:12:14 (1 occurrences)
Last logged: 23:12:14

Unable to prepare setup for platform astroweather.weather: Platform not found (cannot import name 'WeatherEntityFeature' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)).
```

**Comment by L4p3K** [comment]
Okay, thanks for the info. Will do that later, not at the moment.

**Comment by L4p3K** [comment]
Thanks for the info: will do that as soon as possible.

**Comment by L4p3K** [comment]
Yep, updating solved the issue. Thanks for the quick help..
