### ISSUE TITLE
Moon rise/set not correct

### ISSUE THREAD

**Issue by ancjsd** [mawinkler/astroweather#37]
The next moon rise/set calculations don't seem to be correct--at least not for Anchorage, Alaska.  I've confirmed the long/lat and have uninistalled and reinstalled the integration, but the calculations don't jive with those shown at online resources.

**Comment by mawinkler** [comment]
Hi to Alaska,
so, after checking my code, the calculations seem correct in the library. I compared my calculations with the [United States Naval Observatory](https://aa.usno.navy.mil/calculated/rstt/oneday?date=2023-10-21&lat=61.212&lon=-149.737&label=&tz=8&tz_sign=-1&tz_label=false&dst=false&submit=Get+Data)

```
Sun next Rising: 2023-10-21 08:12:20.235611-08:00, Nautical: 2023-10-21 07:22:03.827773-08:00, Astronomical: 2023-10-21 06:31:52.259103-08:00, Astronomical Previous: 2023-10-20 06:29:23.150075-08:00
Sun next Setting: 2023-10-21 19:13:32.885798-08:00, Nautical: 2023-10-21 20:03:40.510739-08:00, Astronomical: 2023-10-21 20:53:39.364195-08:00, Astronomical Previous: 2023-10-20 20:56:26.623536-08:00
Moon next Rising: 2023-10-21 18:10:47.961016-08:00, Moon next Setting: 2023-10-21 22:11:28.824187-08:00, Moon next new Moon: 2023-11-13 00:27:22.323325-09:00
```

What might be confusing, when thinking about it, these datetimes will be converted to the timezone which is set in Home Assistant. I thought this would be a good idea for remote observatory scenarios. Let me know what you think.

**Comment by mawinkler** [comment]
My Backyard scope is 10hs ahead your time
<img width="991" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/110de18c-cd67-4a9c-9544-bbae0c6e234d">
So I can easily see, that when I have 18:12 it's civil twilight in Anchorage.

**Comment by ancjsd** [comment]
![Screenshot_20231021_090728_Home Assistant](https://github.com/mawinkler/astroweather/assets/108994179/fedec47c-f7c4-4704-b32c-51e17057a656)

**Comment by ancjsd** [comment]
Thnanks for the respose!  Just posted screenshot of what my sensor is returning for next moon rising on 10/21:  6:26pm instead of 6:10pm.  Doesnt seem to be a timezone issue.  Am I reading something incorrectly?

**Comment by ancjsd** [comment]
And here's a shot of the sensor state

![Screenshot_20231021_092028_Home Assistant](https://github.com/mawinkler/astroweather/assets/108994179/101f5700-3dad-440b-9e52-fd4240d3d96f)

**Comment by mawinkler** [comment]
So you mean the 16 min difference?
Try to change the pyastroweatherio version in your manifest to 0.40.0. Should be more accurate

**Comment by ancjsd** [comment]
The difference changes from day to day.  Yesterday it was 42 minutes off.   But I'll give that a try.  Thanks.

**Comment by ancjsd** [comment]
Just installed .40 --  Unfortunately it didn't help.

**Comment by mawinkler** [comment]
Honestly I have no idea what's wrong.

If I compare the calculations with the calculations of the [Naval Observatory Risings and Settings](https://aa.usno.navy.mil/data/RS_OneDay) I do get a perfect match for multiple tested locations, including Anchorage:

```
    astroweather = AstroWeather(
        latitude=61.212,
        longitude=-149.737,
        elevation=115,
        timezone_info="America/Anchorage",
        cloudcover_weight=3,
        seeing_weight=2,
        transparency_weight=1,
        uptonight_path="."
    )
```

results:
```
Sun next Rising: 2023-10-22 08:14:49.408726-08:00, Nautical: 2023-10-22 07:24:28.537382-08:00, Astronomical: 2023-10-22 06:34:20.245163-08:00, Astronomical Previous: 2023-10-21 06:31:52.315204-08:00
Sun next Setting: 2023-10-22 19:10:46.310892-08:00, Nautical: 2023-10-22 20:00:58.562102-08:00, Astronomical: 2023-10-22 20:50:54.576962-08:00, Astronomical Previous: 2023-10-21 20:53:39.375619-08:00
Moon next Rising: 2023-10-22 18:09:41.285471-08:00, Moon next Setting: 2023-10-21 22:11:28.787071-08:00, Moon next new Moon: 2023-11-13 00:27:22.323301-09:00
```

<img width="660" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/c83be36e-9e2d-44b6-96ec-e24d97d58f9f">

<img width="846" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/b19431cf-176d-4643-b499-38fbe6e7783b">

Are you far away from this location?

**Comment by ancjsd** [comment]
I'm very close to that location.  As a test, I plugged in the exact same coordinates you used, and my setup returned different values than the National Observatory.  For Octoxber 23, Moon rise was off by 9 minutes, and moon set was off by 12.  I uninstalled and reinstalled and the values were still incorrect--but by different amounts.  Very strange.

**Comment by ancjsd** [comment]
A friend is having the same issue with his moon rise and set that I am.  We're getting identical incorrect values.  Both of us are running HA in VMWare.  Could that be the issue somehow?

**Comment by mawinkler** [comment]
I'm currently in the process of bugfixing and enhancing the astronomical calculations. There's no new release yet, still, but you can try to install the integration and card from main. Here's the Changelog so far:

### Fixes

- Fixed weired behaviour of rise and set calclations depending on the earth location.
- Fixed the Deep Sky Darkness calculation which was a tough one.
- Fixed errors at astronomical night and forecast visualization in the Lovelace card.

I spent hours on testing all the calculations for multiple geographic locations (Anchorage, Sydney, London and my location (nearby Munich)). All show a deviation of less than a couple of seconds compared to United States Naval Observatory. Please report any issues.

### Changes

- Moon set and rise time now calculated according to Naval Observatory Risings and Settings.
- Optional integration with [UpTonight](https://github.com/mawinkler/uptonight).
- Added Slovak translation. Thanks to @misa1515.
- New sensor on request: Next full Moon.
- New binary sensor for moon down during astronomical night.
- Card now displays local time for remote locations.

**Comment by mawinkler** [comment]
This is my current dashboard for testing :-) (UTC+1)
<img width="1674" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/eae084dd-c42b-4800-bb18-669309003a4d">

**Comment by ancjsd** [comment]
Very happy to report that the update appears to be returning correct values for me now. Thanks for a great integration!
