### ISSUE TITLE
Astroweather

### ISSUE THREAD

**Issue by raven19791979** [mawinkler/astroweather#4]
Integracja przestała działać.

**Comment by mawinkler** [comment]
What kind of error do you see? On my side everything looks fine

**Comment by raven19791979** [comment]
The problem was on my side but everything is already ok. Thank you for a
quick answer.

czw., 4 lis 2021, 08:24 użytkownik Markus Winkler ***@***.***>
napisał:

**Comment by mawinkler** [comment]
Thank you for responding.
