### ISSUE TITLE
Unable to add the Integration to Home Assistant

### ISSUE THREAD

**Issue by ggonmar** [mawinkler/astroweather#41]
After having installed the repo via HACS, when I go to Settings > Devices & Services and I try to Astroweather as new integration, it simply freezes on the loading of the integration:

![image](https://github.com/mawinkler/astroweather/assets/11583288/213a64d4-c1b9-44ca-98f3-d7336d04257a)

I could not find any related logs under System to see what may be happening. 
On DevTools, I see a "flow" fetch request that is not being resolved, initiated on `fetch-with-auth.ts:20`. 

Do please let me know if I can provide any further context or if this is not a bug, as I am soooo eager to get this working on my setup!

Thanks!

**Comment by mawinkler** [comment]
I just published a fix release a minute ago. Please go to HACS and the AstroWeather integration and press update information. Then download the version 0.42.1. This should hopefully do the trick.

**Comment by ggonmar** [comment]
Got it working! thank you!
