### ISSUE TITLE
Could Find This in Store

### ISSUE THREAD

**Issue by ispybadguys** [mawinkler/astroweather#42]
I was so impressed with your Astrolabe that I built an HA installation to use them but I can't find it in the Add-on store. Can you point me in th right direction?

Kurt

**Comment by mawinkler** [comment]
Astrolabe? Do you mean AstroLive? If so, it's not in HACS but runs next to Home Assistant

**Comment by ispybadguys** [comment]
Sorry dang spell checker. Ok I thought I saw that it was in the store. my mistake.
