### ISSUE TITLE
sensor.astroweather_moon_next_rising not updating unless rebooted

### ISSUE THREAD

**Issue by tamorgen** [mawinkler/astroweather#46]
I've been noticing that on my dashboard that the Moonrise and Moonset projection shows as in the past and doesn't update unless I reboot Home Assistant.

The current values from HA in the developer tools:

sensor.astroweather_moon_next_risingAstroweather Moon Next Rising | 2023-12-11T11:05:00+00:00
sensor.astroweather_moon_next_settingAstroweather Moon Next Setting | 2023-12-10T19:47:53+00:00

The date of this post is 12/13/2023 @ 1515 EST.

**Comment by mawinkler** [comment]
does the issue still exist for you?

**Comment by tamorgen** [comment]
> does the issue still exist for you?

No, the issue seems to have been resolved.
