### ISSUE TITLE
Depreciations in core 2024.1

### ISSUE THREAD

**Issue by tomlut** [mawinkler/astroweather#48]
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 13:51:47 (12 occurrences)
Last logged: 13:51:50

TEMP_CELSIUS was used from astroweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/mawinkler/astroweather/issues

https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation/

**Comment by mawinkler** [comment]
Relevant PR just merged
