### ISSUE TITLE
Add possibility to give different locations a name

### ISSUE THREAD

**Issue by MarkusH1975** [mawinkler/astroweather#53]
Hi, 

please add the possibility to give different locations a name, e.g. city name.
And make that names part of the entity to make it possible to search / filter for it. 

Like:
sensor.astroweather_MyLocationName_SensorName

Thanks a lot!

**Comment by mawinkler** [comment]
Hi,
Added to my plan. Thanks for requesting this.

Next, the calculation takes into account how little or much wind is to be expected. Will take care of the naming afterwards.

Cheers

**Comment by mawinkler** [comment]
Fixed with release [0.50.0](https://github.com/mawinkler/astroweather/releases/tag/v0.50.0).
