### ISSUE TITLE
suddenly failing with the following error

### ISSUE THREAD

**Issue by fuzzysb** [mawinkler/astroweather#56]
I hope you can assist in the error that i am now receiving in home assistant: 7timer as far as i can see does not use a certificate

![image](https://github.com/mawinkler/astroweather/assets/16162689/f17deadc-8212-499e-b3ad-f3b4f874856a)

**Comment by Elderwolf1700** [comment]
Came to say I am receiving the same error.
Error log:

`This error originated from a custom integration.`

`Logger: custom_components.astroweather
Source: helpers/update_coordinator.py:315
integration: AstroWeather (documentation, issues)
First occurred: 3:38:38 AM (43 occurrences)
Last logged: 4:26:06 AM`

`Unexpected error fetching astroweather data: Error requesting data: Cannot connect to host www.7timer.info:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.7timer.info'. (_ssl.c:1000)")]`
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 102, in get_location_data
    return await self._get_location_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 128, in _get_location_data
    await self.retrieve_data_seventimer()
  File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 597, in retrieve_data_seventimer
    json_data_astro = await self.async_request_seventimer("astro", "get")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
 ` File "/usr/local/lib/python3.12/site-packages/pyastroweatherio/client.py", line 646, in async_request_seventimer
    raise RequestError(f"Error requesting data: {err}") from None
pyastroweatherio.errors.RequestError: Error requesting data: Cannot connect to host www.7timer.info:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.7timer.info'. (_ssl.c:1000)")]`

**Comment by mawinkler** [comment]
Confirmed.
7Timers availability is currently unreliable. It is used for the source for seeing, transparency, and lifted index. For this reason some more error handling is now implemented in [pyastroweatherio](https://github.com/mawinkler/pyastroweatherio) to allow AstroWeather to function even if there is no data available from 7Timer. Condition forecast is then based on clouds and calmness (with an upcoming version of AsterWeather) only. 

If anyone knows a free API source a seeing forecast, please report back.

For now, please change the `manifest.json` in the `custom_components/astroweather` folder to the following:

```yaml
    "requirements": [
        "pyastroweatherio==0.43.1.dev7"
    ],
```

Example of bad weather:
<img width="391" alt="image" src="https://github.com/mawinkler/astroweather/assets/16704258/ad44a84e-cb48-4bcc-b00c-8be105b29e6d">

**Comment by Elderwolf1700** [comment]
I know Accuweather has a "free" API. You can do only so many requests per day before it cuts you off and all you need is an API key from their website.

**Comment by fuzzysb** [comment]
worth noting here that this is a bigger issue than reliability

the certificate used now is a squarespace wildcard cert

![image](https://github.com/mawinkler/astroweather/assets/16162689/7a42ce8b-85cb-415b-8c7d-7d82021257e8)

we don’t need to use SSL though. there is no redirect from http → https, and it seems that the SSL part of this site goes to a squarespace under construction holding page

![image](https://github.com/mawinkler/astroweather/assets/16162689/ef169a61-0958-405e-a80e-3355c58861da)

and the non SSL rewrites to http://167.99.8.254/

https://community-assets.home-assistant.io/original/4X/e/a/8/ea890ef6925abe316c13b2fc32f0ed2fb9527fde.png

shenanigans for sure, the IP 167.99.8.254 is a digital ocean site. I think what they should be doing is getting the likes of cloudflare infront of this and transferring the DNS away from squarespace.

**Comment by danielbrunt57** [comment]
> change the `manifest.json` in the `custom_components/astroweather`

I made the change, restarted HA, and the integration is now running.

**Comment by fuzzysb** [comment]
> > change the `manifest.json` in the `custom_components/astroweather`
> 
> I made the change, restarted HA, and the integration is now running.
> 
> ![image](https://private-user-images.githubusercontent.com/49846893/324523621-080af739-f77d-4df5-ac76-79025f21d435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE4NDYsIm5iZiI6MTcxMzgwMTU0NiwicGF0aCI6Ii80OTg0Njg5My8zMjQ1MjM2MjEtMDgwYWY3MzktZjc3ZC00ZGY1LWFjNzYtNzkwMjVmMjFkNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODM2OWFmOWI1NWQxZTRmMjRlZjkxOWZmNWRkMTBlYTU5MWRiMGRmYWIxM2I4OTZmYmUzZWM0ODY2NzE0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZJJLuAi_tjx9ixtdbXOqP_Vbs2ZRBVbch9Phy79KNTw)

very strange as mine does not after the change and restart of home assistant

**Comment by Elderwolf1700** [comment]
Same here, mine won't load either.

**Comment by Maddin1684** [comment]
> > change the `manifest.json` in the `custom_components/astroweather`
> 
> I made the change, restarted HA, and the integration is now running.
> 
> ![image](https://private-user-images.githubusercontent.com/49846893/324523621-080af739-f77d-4df5-ac76-79025f21d435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjA0ODIsIm5iZiI6MTcxMzg2MDE4MiwicGF0aCI6Ii80OTg0Njg5My8zMjQ1MjM2MjEtMDgwYWY3MzktZjc3ZC00ZGY1LWFjNzYtNzkwMjVmMjFkNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNWY0MTRkNGY4NDY3OWQ0NzYzMWJjOGVhZWE0MDRhYzY3YTQ5NmM0Y2IzYjY1ZGY2ZWYzNzUxMzU5OGU5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.95opqBuCLkAKGv_-myDxCVCWlatpYh_GCxaYFjqaQIw)

Same for me. 
after the change, integration works. 
Will we get an update?

**Comment by mawinkler** [comment]
So, the 7timer service is still down and is currently being discussed in the issue tracker of 7timer.
I'm thinking of replacing 7timer with some seeing estimations based on math :-) let's see how good this will match the "official" services like meteoblue for which no free API is available.
So yes, I will work on an update/alternative for sure, but time is limited at the moment.

**Comment by Maddin1684** [comment]
Thanks for your work!

But moon data is not affected?
(Moonrise and Moonset) should now work with the new string in manifest.json?

**Comment by danielbrunt57** [comment]
@Maddin1684 
> very strange as mine does not after the change and restart of home assistant

I don't know what to say...

**Comment by mawinkler** [comment]
> Thanks for your work!
> 
> But moon data is not affected? (Moonrise and Moonset) should now work with the new string in manifest.json?

Everything besides transparency, seeing, and lifted index should work normally. Things like rising/setting etc. are calculated in AstroWeather.

**Comment by danielbrunt57** [comment]
> Things like rising/setting etc. are calculated in AstroWeather

Or via Node-RED!
See https://community.home-assistant.io/t/my-new-moon-device-from-node-red-node-red-contrib-sun-position/683868

**Comment by tomlut** [comment]
I made the manifest change and restarted, which results in:
```
Logger: pyastroweatherio.client
Source: helpers/update_coordinator.py:271
First occurred: 07:39:14 (1 occurrences)
Last logged: 07:39:14

Error requesting data: Cannot connect to host www.7timer.info2:443 ssl:default [Name does not resolve]
```

![Screenshot 2024-04-24 at 07-40-15 Overview – Home Assistant](https://github.com/mawinkler/astroweather/assets/10679300/546eb0e9-1142-41a2-a153-2cc7ba5c27a4)

**Comment by tomlut** [comment]
And now it is working. Weird. Could have been a cache thing.

**Comment by danielbrunt57** [comment]
> 7timer.info2 [Name does not resolve]

I was thinking along the lines of caching somehow, somewhere as 7timer.info2 doesn't resolve for me either and was going to suggest checking...
![image](https://github.com/mawinkler/astroweather/assets/49846893/66829140-3d16-48b1-8aa2-92a6b097e70b)
but I'm glad it's working for you now!

**Comment by mawinkler** [comment]
Update:
7timer is still down but I'm in contact with the maintainer. The underlying data is functional, but not the API endpoint.
In parallel, I played a little with calculating the seeing myself based on temperature, humidity, wind speed, and altitude which gives some results, but verifying them around the globe with the current unstable weather conditions is hard.

So please be patient, I hope to get AstroWeather up again with not only cloud and wind conditions.

**Comment by freeDom-** [comment]
Thanks for your temporary fix. I can confirm that it is also working for me adter restarting HA.

I really love your intefrarion and want you let to know that I appreciate your woek on this :)

**Comment by mawinkler** [comment]
7timer is up again and AstroWeather should return automatically with the known functionality. I continue to work on the redesign to make AstroWeather more resilient and provide new functionality. In case anyone is curious, there is a redesign branch in all three repos.
Thank you for your patience.

**Comment by danielbrunt57** [comment]
I now have this error...
```
Logger: pyastroweatherio.client
Source: helpers/update_coordinator.py:271
First occurred: 11:52:59 AM (1 occurrences)
Last logged: 11:52:59 AM

Error requesting data: Cannot connect to host www.7timer.info2:443 ssl:default [Name does not resolve]
```
I removed the integration and re-added it but still the same.

```
> 7timer.info2
Server:  dns.google
Address:  8.8.8.8

*** dns.google can't find 7timer.info2: Non-existent domain
```
