### ISSUE TITLE
HomeAssistantType is a deprecated alias

### ISSUE THREAD

**Issue by tomlut** [mawinkler/astroweather#57]
Testing HA core 2024.5.b0 produces this error:

HomeAssistantType was used from astroweather, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'astroweather' custom integration

**Comment by mawinkler** [comment]
Will take care on this during redesign phase.

**Comment by mawinkler** [comment]
Fixed in redesign branch and will make it to main whenever redesign is done.

**Comment by mawinkler** [comment]
Fixed with release [0.50.0](https://github.com/mawinkler/astroweather/releases/tag/v0.50.0).
