### ISSUE TITLE
moon_next_rising updating too early

### ISSUE THREAD

**Issue by beorn59** [mawinkler/astroweather#7]
Hej,

I wanted to set-up an alarm if the moon rises, to be prepared that the werewolfs are out, but noticed that:

The time in the sensor.astroweather_moon_next_rising gets its next day update 2h before the todays time of moon rising is reached. So today in the moring it was saying moonrise is 2022-02-11 11:52 and this switched to 2022-02-12 12:38 at about 10:00. 
The timezone is correct, the moon really rises at 11:52 today.

Is there a way for the sensor to wait until the time of the next rising is really reached, before updating it to the next days rising time?

kind regards
Beorn

**Comment by mawinkler** [comment]
Hi,
need to think about that. The astronomical routines for sun and moon are automatically recalculated whenever home assistant calls get_location_data from pyastroweatherio. This happens pretty frequently and I cannot really explain why you observed that day switch nearly two hours before.
May I ask you about your time zone?
Cheers,
Markus

**Comment by beorn59** [comment]
Hello Markus,

Thank you for taking care. 
I'm located in Germany. My timezone is CET (=UTC+1).
Unfortunately I'm not a developer but tell me if I can support the troubleshooting somehow. 

Kind regards 
Ruslan 


Am 15. Februar 2022 21:26:03 MEZ schrieb Markus Winkler ***@***.***>:
>Hi,
>need to think about that. The astronomical routines for sun and moon are automatically recalculated whenever home assistant calls get_location_data from pyastroweatherio. This happens pretty frequently and I cannot really explain why you observed that day switch nearly two hours before.
>May I ask you about your time zone?
>Cheers,
>Markus
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mawinkler/astroweather/issues/7#issuecomment-1040758061
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mawinkler** [comment]
I think I finally got an idea to solve this. Will change the astronomical routines.

**Comment by mawinkler** [comment]
Solved with AstroWeather version [0.30.0](https://github.com/mawinkler/astroweather/releases/tag/v0.30.0), finally.
